apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mariadb
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mariadb
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:{{ .Values.mariadb.tag }}
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.credentials.dbName }}
            - name: MYSQL_USER
              value: {{ .Values.mariadb.credentials.userName }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mariadb.credentials.userPwd }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mariadb.credentials.rootPwd }}
          ports:
            - containerPort: 3306

