apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
spec:
  topologySpreadConstraints:           
  - maxSkew: 1             
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule             
    labelSelector:                
      matchLabels:                 
        app: {{ .Release.Name }}-web
  replicas: 3 
  selector:
    matchLabels:
      app: {{ .Release.Name }}-web
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-web
    spec:
      containers:
        - name: web
          image: {{ .Values.web.image }}:{{ .Values.web.tag }} 
          ports:
            - containerPort: 3000
          env:
            - name: TYPEORM_HOST
              value: {{ .Release.Name }}-mariadb-service
      imagePullSecrets:
        - name: regcred
