apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  selector:
    ingressClassName: ngninx
    rules:
    - host: 3000
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80