apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: igor1945/app:v1
          ports:
            - containerPort: 3000
          env:
            - name: TYPEORM_HOST
              value: mariadb-service
     
     # initContainers:
      #  - name: init-myservice
       #   image: igor1945/app:v1
        #  command: ['yarn', 'typeorm', 'migration:run']
---

apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP